---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: single-app-single-collector
  labels:
    app: single-app-single-collector
  namespace: metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: single-app-single-collector
  template:
    metadata:
      labels:
        app: single-app-single-collector
      annotations:
        instrumentation.opentelemetry.io/inject-python: "true"
        # instrumentation.opentelemetry.io/otel-python-platform: "glibc" # for Linux musl based images
        instrumentation.opentelemetry.io/otel-python-platform: "musl" # for Linux musl based images
        resource.opentelemetry.io/service.name: "dice-python"
        resource.opentelemetry.io/service.namespace: "game"
        resource.opentelemetry.io/service.version: "1.2.3"
        resource.opentelemetry.io/deployment.environment.name: "production"
    spec:
      containers:
      - name: single-app-single-collector
        imagePullPolicy: Always
        image: rutush10/otel-autoinstrumentation-fastapi-simple-app:0.0.4
        ports:
          - containerPort: 8000
        envFrom:
          - configMapRef:
              name: single-app-single-collector
        resources:
          limits:
            memory: "1Gi"
            cpu: "0.5"
          requests:
            memory: "1Gi"
            cpu: "0.5"